config/routes.rb
Rails.application.routes.draw do

  root to: 'homes#top'

  get 'kanri' => "homes#kanri"

  get 'kanri/new' => "homes#new"

  resources :news, only: [:create, :edit, :update, :destroy]
  resources :partners, only: [:create, :edit, :update, :destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/news.rb
class News < ApplicationRecord

end

app/models/partner.rb
class Partner < ApplicationRecord

  attachment :partner_image

  enum tag_id: {
    '1: ARTIST':1,
    '2: DJ':2,
    '3: ART':3,
    '4: PERFORMER':4,
    '5: TIE UP':5,
    '6: KITCHEN CAR':6,
    '7: others':7
  }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    @newsall = News.all.where(published: true).order(year: :desc).order(month: :desc).order(date: :desc)
    @artistsall = Partner.all.where(tag_id: 1).order(name: :asc)
    @partners = Partner.all.where(published: true).order(name: :asc)
  end

  def kanri
    @newsall = News.all.order(year: :desc).order(month: :desc).order(date: :desc)
    @partnersall = Partner.all.order(tag_id: :asc).order(name: :asc)
  end

  def new
    @news = News.new
    @partner = Partner.new
  end

  private

  def news_params
    params.require(:news).permit(:year, :month, :date, :title, :published)
  end

end

app/controllers/news_controller.rb
class NewsController < ApplicationController

  def new
    @news = News.new
    date = params[:date]

  end

  def create
    @news = News.new(news_params)
    @news.save
    redirect_to root_path
  end

  def edit
    @news = News.find(params[:id])
  end

  def update
    @news = News.find(params[:id])
    if @news.update(news_params)
      flash[:notice] = "NEWSが更新されました！"
      redirect_to kanri_path
    else
      render 'edit'
    end
  end

  def destroy
    news = News.find(params[:id])
    news.destroy
    flash[:notice] = "NEWSが削除されました！"
    redirect_to kanri_path
  end

  private

  def news_params
    params.require(:news).permit(:year, :month, :date, :title, :published)
  end

end

app/controllers/partners_controller.rb
class PartnersController < ApplicationController

  def new
    @partner = Partner.new
  end

  def create
    @partner = Partner.new(partner_params)
    if @partner.save
      redirect_to root_path
    else
      redirect_to kanri_new_path
    end
  end

  def edit
    @partner = Partner.find(params[:id])
  end

  def update
    @partner = Partner.find(params[:id])
    if @partner.update(partner_params)
      flash[:notice] = "パートナー情報が更新されました！"
      redirect_to kanri_path
    else
      render 'edit'
    end
  end

  def destroy
    partner = Partner.find(params[:id])
    partner.destroy
    flash[:notice] = "パートナー情報が削除されました！"
    redirect_to kanri_path
  end

  private

  def partner_params
    params.require(:partner).permit(:partner_image, :link, :name, :tag_id, :published)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/partners_helper.rb
module PartnersHelper
end

app/views/homes/kanri.html.erb
<h1 style="font-size: 50px; text-align: center; margin-top: 100px">【管理画面】</h1>

  <div class="news-container" id="news">
    <h2 id="title" class="news-title">
      ＮＥＷＳ（管理画面）
    </h2>

    <%= button_to "NEWS新規作成", {controller: 'homes', action: 'new'}, {method: :get, class: "create-link"} %>

    <% @newsall.each do |news| %>
      <div class="news-box">
        <span class="news-text-date blk-opc">
          <%= news.year %>.<%= news.month %>.<%= news.date %>
        </span>
        <span class="news-text-title blk-opc">
          <%= news.title %>
        </span><br>
        <span class="news-text-date blk-opc">
          <%#= news.published %>
          <% if news.published == true %>
            <span class="published blk-opc">公開中</span>
          <% elsif news.published == false %>
            <span class="draft blk-opc">下書き</span>
          <% end %>
        </span>
        <span class="news-text-edit blk-opc">
          <%= link_to "[編集]", edit_news_path(news.id), class: "blk-opc" %>
        </span>
        <span class="news-text-edit blk-opc">
          <%= link_to "[削除]", news_path(news.id), method: :delete, data: {confirm: "注意：この操作は取り消せません。削除してよろしいですか？"}, class: "blk-opc" %>
        </span>
      </div>
    <% end %>

  </div>



  <div class="news-container" id="news">
    <h2 id="title" class="news-title">
      ＰＡＲＴＮＥＲＳ（管理画面）
    </h2>

    <%= button_to "PARTNERS新規作成", {controller: 'homes', action: 'new'}, {method: :get, class: "create-link"} %>

    <% @partnersall.each do |p| %>
      <div class="kanri-p clearfix">
        <%= attachment_image_tag p, :partner_image, format: 'jpeg', fallback: "", class: "kanri-p-image" %>
        <div class="kanri-p-text blk-opc">
          名前：　　<%= p.name %><br>
          URL：　　<%= link_to p.link do %>
                    <%= p.link %>
                  <% end %><br>
          タグ：　　<%= p.tag_id %><br>
          状態：　　<span class="news-text-date blk-opc">
                    <% if p.published == true %>
                      <span class="published blk-opc">公開中</span>
                    <% elsif p.published == false %>
                      <span class="draft blk-opc">下書き</span>
                    <% end %>
                  </span><br>
          操作：　　<%= link_to "[編集]", edit_partner_path(p.id), class: "blk-opc" %>
          　　<%= link_to "[削除]", partner_path(p.id), method: :delete, data: {confirm: "注意：この操作は取り消せません。削除してよろしいですか？"}, class: "blk-opc" %>
        </div>
      </div>

      <!-- <div class="news-box"> -->
      <!-- </div> -->
    <% end %>

  </div>

app/views/homes/new.html.erb
<div class="create-news">
  <h1>新規投稿（ニュース）</h1>
  <!-- form_for部分 -->
  <%#= form_for @news, :url => {controller: "news", action: "new"} do |f| %>
  <%= form_for @news do |f| %>

    <h4>日付</h4>
    <%#= date_field_tag :date %>
    <%= f.number_field :year, class: "create-news-date" %>年　
    <%= f.number_field :month, class: "create-news-date" %>月　
    <%= f.number_field :date, class: "create-news-date" %>日

    <h4>タイトル</h4>
    <%= f.text_area :title, class: "create-news-title" %>

    <h4>公開非公開</h4>
    <%= f.select :published, {'公開': 1, '下書き': 0}, {include_blank: ''}, { class: '' , required: true } %>

    <%= f.submit '投稿' %>

  <% end %>

</div>

<div class="create-news">
  <h1>新規投稿（パートナー情報）</h1>
  <!-- form_for部分 -->
  <%#= form_for @news, :url => {controller: "news", action: "new"} do |f| %>
  <%= form_for @partner do |f| %>

    <h4>画像</h4>
      <div class="">
        <%#= f.attachment_field :partner_image, direct: true, presigned: true %>
        <%= f.attachment_field :partner_image %>
      </div>

    <h4>リンク先</h4>
    <%= f.text_field :link, class:"create-partner-link" %>

    <h4>名前</h4>
    <%= f.text_field :name, class:"create-partner-link" %>

    <h4>タグ</h4>
    <%= f.select :tag_id, Partner.tag_ids.keys, { prompt: '選択してください' } %>

    <h4>公開非公開</h4>
    <%= f.select :published, {'公開': 1, '下書き': 0}, {include_blank: ''}, { class: '' , required: true } %>

    <%= f.submit '保存' %>

  <% end %>

</div>

app/views/homes/top.html.erb
<%= render 'layouts/header' %>




  <div class="top-container top-opacity">
    <div class="top-box top-opacity">
      <img src="images/hero-logo.png" alt="title" class="top-img top-opacity">
    </div>
  </div>



  <div class="about-container" id="about">
    <h2 id="title" class="about-title">
      ABOUT
    </h2>
    <p class="about-text">
      「HANAVIVA 2020 powered by POMATO PRO（以下：HANAVIVA）」は<br>
      横浜港大さん橋国際客船ターミナルを舞台に、アート・ミュージック・フードなど、<br>
      様々なカルチャーを楽しむことのできるプログラムと、横浜スパークリングトワイライト スパークリング花火を、<br>
      目の前で鑑賞し、“ココロ揺さぶる時間“ を過ごすことのできる1日限りの総合フェスティバル。<br>
    </p>
    <p class="about-subtext">
      ※横浜スパークリングトワイライトの詳しい情報は公式HPよりご覧ください。<br>
      <%= link_to 'https://yokohama-sparkling.com/', 'https://yokohama-sparkling.com/', class: 'blk-opc underline' %>
    </p>

    <div class="about-box">
      <h4 class="about-box-title">
        『HANAVIVA 2020 Powered by POMATO PRO』
      </h4>
      <p class="about-box-text">
        日時：2020年7月18日(土) OPEN 14:00 CLOSE 21:00 ※予定<br>
        会場：横浜港大さん橋国際客船ターミナル特設会場<br>
      </p>
      <p class="about-box-text-sub">
        （神奈川県横浜市中区海岸通１丁目1番4号）
      </p>
    </div>

    <div class="about-img">
      <img src="images/about-img.jpg" alt="title" class="about-img">
    </div>
  </div>



  <div class="news-container" id="news">
    <h2 id="title" class="news-title">
      NEWS
    </h2>

    <% @newsall.each do |news| %>
      <div class="news-box">
        <span class="news-text-date blk-opc">
          <%= news.year %>.<%= news.month %>.<%= news.date %>
        </span>
        <span class="news-text-title blk-opc">
          <%= news.title %>
        </span>
      </div>
    <% end %>
  </div>



  <div class="cast-container" id="cast">
    <h2 id="title" class="cast-title">
      CAST
    </h2>

    <p class="cast-tag">
      ARTIST
    </p>

    <div class="clearfix">
      <% @partners.where(tag_id: 1).each do |p| %>
        <div class="cast-box">
          <div class="cast-image">
            <%= link_to p.link do %>
              <%= attachment_image_tag p, :partner_image, format: 'jpeg', fallback: "", class: "cast-image" %>
              <%#= attachment_image_tag p, :partner_image, format: 'jpeg', fallback: "", size: "480x228", class: "" %>
            <% end %>
          </div>
          <div class="cast-name">
            <%= p.name %>
          </div>
        </div>
      <% end %>
    </div>

    <p class="kana-order">
      ※50音順
    </p>

    <p class="cast-tag">
      DJ
    </p>

    <div class="clearfix">
      <% @partners.where(tag_id: 2).each do |p| %>
        <div class="cast-box">
          <div class="cast-image">
            <%= link_to p.link do %>
              <%= attachment_image_tag p, :partner_image, format: 'jpeg', fallback: "", class: "cast-image" %>
              <%#= attachment_image_tag p, :partner_image, format: 'jpeg', fallback: "", size: "480x228", class: "" %>
            <% end %>
          </div>
          <div class="cast-name">
            <%= p.name %>
          </div>
        </div>
      <% end %>
    </div>

    <p class="kana-order">
      ※50音順
    </p>

    <p class="cast-tag">
      ART
    </p>

    <div class="clearfix">
      <% @partners.where(tag_id: 3).each do |p| %>
        <div class="cast-box">
          <div class="cast-image">
            <%= link_to p.link do %>
              <%= attachment_image_tag p, :partner_image, format: 'jpeg', fallback: "", class: "cast-image" %>
              <%#= attachment_image_tag p, :partner_image, format: 'jpeg', fallback: "", size: "480x228", class: "" %>
            <% end %>
          </div>
          <div class="cast-name">
            <%= p.name %>
          </div>
        </div>
      <% end %>
    </div>

    <p class="kana-order">
      ※50音順
    </p>

    <p class="cast-tag">
      PERFORMERS
    </p>

    <div class="clearfix">
      <% @partners.where(tag_id: 4).each do |p| %>
        <div class="cast-box">
          <div class="cast-image">
            <%= link_to p.link do %>
              <%= attachment_image_tag p, :partner_image, format: 'jpeg', fallback: "", class: "cast-image" %>
              <%#= attachment_image_tag p, :partner_image, format: 'jpeg', fallback: "", size: "480x228", class: "" %>
            <% end %>
          </div>
          <div class="cast-name">
            <%= p.name %>
          </div>
        </div>
      <% end %>
    </div>

    <p class="kana-order">
      ※50音順
    </p>

  </div>



  <div class="fooddrink-container" id="fooddrink">
    <h2 id="title" class="fooddrink-title">
      FOOD&DRINK
    </h2>

    <img src="images/img-food.jpg" alt="title" class="fd-img">

    <p class="kana-order">
      ※VIP席、指定席のお客様のFOOD & DRINKのイメージです
    </p>

    <p class="cast-tag">
      TIE UP
    </p>

    <div class="clearfix">
      <% @partners.where(tag_id: 5).each do |p| %>
        <div class="cast-box">
          <div class="cast-image">
            <%#= link_to p.link do %>
              <%= attachment_image_tag p, :partner_image, format: 'jpeg', fallback: "", class: "cast-image" %>
              <%#= attachment_image_tag p, :partner_image, format: 'jpeg', fallback: "", size: "480x228", class: "" %>
            <%# end %>
          </div>
          <div class="cast-name">
            <%= p.name %>
          </div>
        </div>
      <% end %>
    </div>

    <p class="kana-order">
      ※アルファベット順
    </p>
    <p class="kana-order">
      ※VIP席、指定席のお客様のFOOD & DRINKのイメージです
    </p>

  </div>



  <div class="ticket-container" id="ticket" style="height: 1000px">
    <h2 id="title" class="ticket-title">
      TICKET
    </h2>

    <p class="cast-tag">
      CONTACT
    </p>
    <p class="about-text" style="margin-bottom: 40px">
      連日たくさんのお問い合わせいただいております。<br>
      以下のフォームよりお気軽にご連絡ください。
    </p>

  <%#= form_for @partner do |f| %>

  <div style="width: 500px; height:500px; margin:0 auto">
    <h4>お名前</h4>
    <%#= f.text_field :link, style: "width:500px" %>

    <br><br>
    <h4>お問い合わせ内容</h4>
    <%#= f.text_area :name, style: "width:500px; height: 200px" %>

    <br><br>
    <%#= f.submit '送信' %>
  </div>
  <%# end %>


  </div>



  <div class="access-container clearfix" id="access">
    <h2 id="title" class="access-title">
      ACCESS
    </h2>

    <div class="access-map">
      <iframe src="https://maps.google.co.jp/maps?output=embed&q=神奈川県横浜市中区海岸通１丁目1番4号" class="iframe" allowfullscreen></iframe>
    </div>

    <div class="access-box">
      <p class="access-box-text">
        会場<br>
        <span style="font-size: 14px; font-weight: 200; display: inline-block">横浜港大さん橋国際客船ターミナル HANAVIA2019 特設会場</span><br>
        <span style="font-size: 11px; font-weight: 100; display: inline-block">〒231-0002 神奈川県横浜市中区海岸通１丁目1番4号</span><br>
        <br>
        最寄り駅<br>
        <span style="font-size: 14px; font-weight: 200; display: inline-block">みなとみらい線「日本大通り駅」3番出口より 約7分</span>
      </p>
    </div>
  </div>



  <div class="report-container" id="report" style="height: 950px">
    <h2 id="title" class="report-title">
      REPORT
    </h2>
  </div>

app/views/layouts/_header.html.erb
<div class="navbar clearfix">

  <!-- header 左側 -->
  <div class="header-left">
    <%= link_to image_tag("logo-top.png", class:"logo-top"), root_path %>
  </div>

  <!-- header 中央 -->
  <div class="header-center">
    <div class="header-box">
      <%= link_to 'ABOUT', '#about', class: 'header-center-text' %>
    </div>
    <div class="header-box">
      <%= link_to 'NEWS', '#news', class: 'header-center-text' %>
    </div>
    <div class="header-box">
      <%= link_to 'CAST', '#cast', class: 'header-center-text' %>
    </div>
    <div class="header-box">
      <%= link_to 'FOOD&DRINK', '#fooddrink', class: 'header-center-text' %>
    </div>
    <div class="header-box">
      <%= link_to 'TICKET', '#ticket', class: 'header-center-text' %>
    </div>
    <div class="header-box">
      <%= link_to 'ACCESS', '#access', class: 'header-center-text' %>
    </div>
    <div class="header-box">
      <%= link_to 'REPORT', '#report', class: 'header-center-text' %>
    </div>
  </div>

  <!-- header 右側 -->
  <div class="header-right">
    <h4>
    </h4>
  </div>

    <span style="position: absolute; top: 5px; right: 5px; font-size: 11px; color: orange">
      ※こちらはダミーサイトです。掲載されている情報は事実と異なります。
    </span>

</div>

<div class="gradient-bar">
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>lp83</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta name="viewport" content="width=device-width,initial-scale=1.0">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/news/edit.html.erb
<div class="create-news">
  <h1>新規投稿（ニュース）</h1>
  <!-- form_for部分 -->
  <%#= form_for @news, :url => {controller: "news", action: "new"} do |f| %>
  <%= form_for @news do |f| %>

    <h4>日付</h4>
    <%#= date_field_tag :date %>
    <%= f.number_field :year, class: "create-news-date" %>年　
    <%= f.number_field :month, class: "create-news-date" %>月　
    <%= f.number_field :date, class: "create-news-date" %>日

    <h4>タイトル</h4>
    <%= f.text_area :title, class: "create-news-title" %>

    <h4>公開非公開</h4>
    <%= f.select :published, {'公開': 1, '下書き': 0}, {include_blank: ''}, { class: '' , required: true } %>

    <%= f.submit '更新' %>

  <% end %>

</div>

app/views/partners/edit.html.erb
<div class="create-news">
  <h1>新規投稿（パートナー情報）</h1>
  <!-- form_for部分 -->
  <%#= form_for @news, :url => {controller: "news", action: "new"} do |f| %>
  <%= form_for @partner do |f| %>

    <h4>画像</h4>
      <div class="">
        <%#= f.attachment_field :partner_image, direct: true, presigned: true %>
        <%= f.attachment_field :partner_image %>
      </div>

    <h4>リンク先</h4>
    <%= f.text_field :link, class:"create-partner-link" %>

    <h4>名前</h4>
    <%= f.text_field :name, class:"create-partner-link" %>

    <h4>タグ</h4>
    <%= f.select :tag_id, Partner.tag_ids.keys, { prompt: '選択してください' } %>

    <h4>公開非公開</h4>
    <%= f.select :published, {'公開': 1, '下書き': 0}, {include_blank: ''}, { class: '' , required: true } %>

    <%= f.submit '保存' %>

  <% end %>

</div>